### PR TITLE
Use rollup

### PR DESCRIPTION
**Pull request by qm3ster**
replaced gulp build with rollup

Also added example from [highcwu.github.io/waifu2x-tfjs/](https://highcwu.github.io/waifu2x-tfjs/),
which now points directly to models in https://github.com/nagadomi/waifu2x/tree/master/models/vgg_7 through https://cdn.rawgit.com

### CODE REVIEW

**Comment by HighCWu** [comment]
You've done a good job. 
Part of the project is modified from a three-year-before project,  which may be hard for me to update it to these days' frontend process. But you did it .
Thank you for your pull.

**Comment by HighCWu** [comment]
The cdn you provided is not OK on my area, so I'll change it to gitcdn.link later, which should be OK for most devs.

**Comment by qm3ster** [comment]
Didn't know rawgit is banned anywhere or that that other one exists.
https://trends.google.com/trends/explore?date=today%205-y&q=rawgit,gitcdn
Do you know who runs it?

**Comment by HighCWu** [comment]
@qm3ster rawgit is banned in China like many cdn outside China. But some cdn like [http://gitcdn.link/](url) are OK. Maybe they are not discovered by gov's GFW now.

**Pull request merged**
